left to right direction

SuperUser as sudo
Administrator as admin
User as user

package MobileApp {
    user -> (ListExercises)
    user -> (SortExercises)
    user -> (SearchExercises)
    (SearchExercises) .> (ListExercises)
    (SortExercises) .> (ListExercises)
    (ReadText) .> (ListExercises)

    user -> (ReadText)
    user -> (ViewCompletion)
    user -> (ViewReadingProfficiency)
    (ViewCompletion) .> (ReadText)

    user --> (SwitchUser)
    user --> (MobileLogin)
}

package WebApp {
    admin <|-- sudo
    sudo --> (AddAdministrator)
    sudo --> (RemoveAdministrator)
    admin --> (AddText)
    admin --> (RemoveText)
    admin --> (EditText)
    admin --> (EditTextMetadata)
    admin --> (WebLogin)
}
