left to right direction

SuperUser as sudo
Administrator as admin
User as user

package MobileApp {
    user -> (ListExercises)
    user -> (SortExercises)
    user -> (SearchExercises)
    (SearchExercises) .> (ListExercises)
    (SortExercises) .> (ListExercises)
    (ReadExerciseTest) .> (ListExercises)

    user -> (ReadExerciseTest)
    user -> (ViewCompletion)
    user -> (ViewReadingProfficiency)
    (ViewCompletion) .> (ReadExerciseTest)
    (MobileLogout) .> (MobileLogin)

    user --> (SwitchUser)
    user --> (MobileLogin)
    user --> (MobileLogout)
}

package WebApp {
    admin <|-- sudo
    sudo --> (AddAdministrator)
    sudo --> (RemoveAdministrator)
    sudo --> (EditAdministrator)
    sudo --> (ViewAllAdministrators)
    admin --> (ViewAllExercises)
    admin --> (AddTextExercises)
    admin --> (RemoveTextExercises)
    admin --> (EditTextExercises)

    (WebLogout) .> (WebLogin)
    admin --> (WebLogin)
    admin --> (WebLogout)
}

